In [1]:
# Andrew Kan, Govind Pillai

In [79]:
# Initialization
import pandas as pd
import numpy as np
import nltk
import string
lemmatizer = WordNetLemmatizer()
np.set_printoptions(threshold=np.nan)


translator = str.maketrans('', '', string.punctuation)

# Read in data, drop unimportant columns and rename column names to be more descriptive

emails_df = pd.read_csv("./data/spam.csv", encoding= "ISO-8859-1")
emails_df = emails_df.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis=1)
emails_df.columns = ['type', 'body']

emails_smalldf = emails_df.head(5)

stop_words = ["hi"]

def clean(word) :
    cleaned_word = word.translate(translator)
    cleaned_word = lemmatizer.lemmatize(cleaned_word)
    return cleaned_word

In [80]:
word_dict = {}
for i, email in emails_smalldf.iterrows():
    for word in email['body'].split():
        # Remove punctuation and lemmatize
        cleaned_word = clean(word)
    
        if word in word_dict.keys(): 
            word_dict[cleaned_word] += 1
        else: 
            word_dict[cleaned_word] = 1

# Remove stop words      

for key in list(word_dict):
    if key in stop_words:
        del word_dict[key]
# word_dict


# make feature vectors
dictionary_keys = sorted(word_dict.keys(), key=str.lower)
emails_smalldf.shape[0]
feature_vector = np.zeros((emails_smalldf.shape[0], len(dictionary_keys)))
for i, email in emails_smalldf.iterrows():
#     word_vector = np.zeros(len(dictionary_keys))
    for word in email['body'].split():
        cleaned_word = clean(word)
        if cleaned_word in dictionary_keys and cleaned_word not in stop_words:
            feature_vector[i, list(dictionary_keys).index(cleaned_word)] += 1
print(feature_vector)


# word_vector

[[3. 2. 0. 2. 4. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4. 1. 0. 0.]
 [2. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [8]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/govindpillai/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True